name: cicd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: git code checkout
        uses: actions/checkout@v3

      - name: docker setup
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparcs27-fe:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sparcs27-fe:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sparcs27-fe:cache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sparcs27-fe:latest
            docker stop sparcs27-fe || true
            docker rm sparcs27-fe || true
            docker run -d --name sparcs27-fe -p 3000:4173 ${{ secrets.DOCKERHUB_USERNAME }}/sparcs27-fe:latest
